name: Test & Lint

'on':
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - run: npm i
      - run: npm run lint
      - run: npm run test:ci
