name: Deploy

on:
  workflow_dispatch:

jobs:
  test_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - run: npm i
      - run: npm run lint
      - run: npm run test

  deploy:
    needs: test_lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIDEO_EDITOR_25927 }}'
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}


